KeyCase/BoardShop/urls.py
from .views import index, Registation, Login, Products, ProductDetailView, AddToCart, CartView
from django.urls import path
from django.contrib.auth.views import LogoutView

app_name = 'BoardShop'

urlpatterns = [
    path('', index, name='index'),
    path('register/', Registation.as_view(), name='reg'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('products/', Products, name='Product'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='ProductView'),
    path('addToCart/<int:pk>/', AddToCart.as_view(), name='addToCart'),
    path('cart/', CartView.as_view(), name='cart')
]

KeyCase/KeyCase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BoardShop.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KeyCase/BoardShop/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import FileExtensionValidator
# Create your models here.


class User(AbstractUser):
    class Meta(AbstractUser.Meta):
        pass


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=12, decimal_places=2, default=299)
    img = models.ImageField(upload_to='static/img/content', validators=[
                            FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])
    # validators=[FileExtensionValidator(allowed_extensions=['png']), validate_image]

    def __str__(self):
        return self.name


class CartProduct(models.Model):
    user = models.ForeignKey(User, verbose_name='Покупатель', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products')
    price = models.DecimalField(max_digits=12, decimal_places=2)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(
        max_digits=9, decimal_places=2, verbose_name='Общая цена')

    def __str__(self):
        return 'Товар: {}, кол-во: {}'.format(self.product.name, self.qty)
    def save(self, *args, **kwargs):
        self.final_price = self.qty * self.price
        super().save(*args, **kwargs)


class Cart(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    final_price = models.DecimalField(max_digits=12, decimal_places=2, default=0, verbose_name='Общая цена')
    in_order = models.BooleanField(default=False)
    # for_anonymous_user = models.BooleanField(default=False)
    qty = models.PositiveIntegerField(default=0)

KeyCase/BoardShop/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import User

class RegitrationsForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username']

KeyCase/BoardShop/views.py
from django.shortcuts import render
from django.views import generic
from .models import User, Product, CartProduct
from .forms import RegitrationsForm
from .mixins import CartMixin
from .utils import recalc_cart
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.views import LoginView
# КТО Я
# АСКА ТУПО ЛУЧШЕ


def index(request):
    # count = Product.aggregate(count=Count('id'))['count']
    # random_index = randint(0, count - 1)
    # randBoard = Product.objects.all()
    model = Product.objects.order_by('?')[:3]
    return render(request, 'index.html', {'rand': model})


def Products(request):
    model = Product.objects.all()
    return render(request, 'products.html', {'products': model})


class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'product.html'

class AddToCart(CartMixin, generic.View):
    def post(self, request, *args, **kwargs):
        product = Product.objects.get(id=kwargs.get('pk'))
        cart_product, created = CartProduct.objects.get_or_create(
            user=self.cart.owner, cart=self.cart, product=product, price=product.price
        )
        if created:
            self.cart.products.add(cart_product)
        else:
            productQTY = CartProduct.objects.get(
                user=self.cart.owner, cart=self.cart, product=product, price=product.price
            )
            productQTY.qty += 1
            productQTY.save()
        recalc_cart(self.cart)
        return HttpResponseRedirect(reverse('BoardShop:ProductView', args=[kwargs.get('pk')]))

class CartView(CartMixin, generic.View):
    def get(self, request, *args, **kwargs):
        return render(request, 'cart.html', {'cart': self.cart})

class Login(LoginView):
    template_name = 'login.html'

    def get_redirect_url(self):
        if self.request.user.is_superuser or self.request.user.is_staff:
            return '/admin'
        else:
            return '/'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('BoardShop:index'))
        return super().get(request, *args, **kwargs)


class Registation(generic.CreateView):
    template_name = 'registration.html'
    model = User
    form_class = RegitrationsForm
    success_url = reverse_lazy('BoardShop:login')

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('BoardShop:index'))
        return super().get(request, *args, **kwargs)

KeyCase/BoardShop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap"
      rel="stylesheet"
    />
    <title></title>

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="/static/css/static.css" />
  </head>

  <body>
    <div class="navigation d-flex justify-content-between mb-5">
      <nav>
        <a href="/" class="logo"
          ><img href="#" src="/static/img/logo/logo.png" alt=""
        /></a>
        <a class="menu main-item" href="javascript:void(0);" tabindex="1"
          ><img class="menu" src="/static/img/content/меню.png" alt=""
        /></a>
        <div class="sub-menu">
          <a href="/"
            ><img class="logo" href="#" src="/static/img/logo/logo2.png" alt=""
          /></a>
          <a class="navigationPlate navigationPlate1" href="/products"
            >Товары</a
          >
          <a class="navigationPlate navigationPlate2" href="#2">подпункт 2</a>
          <a class="navigationPlate navigationPlate3" href="#3">подпункт 3</a>
        </div>
      </nav>
      <nav class="nav2 ">
        {% if user.is_authenticated %}
        <p><a href=""> {{ user.username }} </a></p>
        <p><a href="/logout">Выйти</a></p>
        {% else %}
        <p><a href="/login">Авторизация</a></p>
        <p><a href="/register">Регистрация</a></p>
        {% endif %}
        <p><a href="/cart">Корзина</a></p>
      </nav>
    </div>
    
    {% block content %} {% endblock %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

KeyCase/BoardShop/templates/cart.html
{% extends 'base.html' %} {% block content %}

<div class="cart">
  {% comment %} {% if cart.products.count %} {% for cart_product in
  cart.products.all %}
  <div class="card-body">
    <img
      src="{{ cart_product.product.img.url }}"
      class="card-img-top"
      alt="..."
      style="border: solid 1px white"
    />
    <h5 class="card-title">{{ cart_product.product.name }}</h5>
    <p>{{ cart_product.qty }}</p>
    <p>{{ cart_product.final_price }} ₽</p>
  </div>

  {% endfor %} {% else %} соси {% endif %}
</div>

{% endcomment %}

<div data-bs-spy="scroll" style="padding: 8px; margin: 8px; color: white" class="border-top border-bottom">
  {% for item in cart.products.all %}
  <div class="row g-0">
    <div class="col-md-1 align-self-center">
      <img
        style="border: solid 1px white"
        src="{{item.product.img.url}}"
        width="100%"
        class="m-auto"
      />
    </div>
    <div class="card-body col-md-5 pr-0 pl-0">
      <div class="p-0 d-inline-block">
        <h3 class="card-title">{{ item.product.name }}</h3>
      </div>
    </div>
    <div
      style="border: solid 1px white"
      class="card-body col-md-1 pr-0 pl-0 justify-content-end"
    >
      <div class="d-flex align-self-center col-md-3 justify-content-end">
        <span style="margin-right: 15px;">Колво:{{ item.qty }}</span>
        <span> {{ item.final_price }}₽</span>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
<p style="color: white;  margin-right: 15px;" class="text-end">{{cart.final_price}} ₽</p>
{% endblock content %}

KeyCase/BoardShop/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators  buttonFloat divFloat">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0"
            class="active buttonFloat" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" class="buttonFloat"
            aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" class="buttonFloat"
            aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        {% for i in rand %}
        {% if forloop.first %}
        <div class="carousel-item active">
            <img src="{{i.img.url}}" class="d-block w-100 carousel-img" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h1 class="carouselTextH1">{{i.name}}</h1>
                <p>{{i.description|truncatechars:250}}</p>
                <a href="{% url 'BoardShop:ProductView' i.id%}"><button type="button"
                        class="btn btn-dark border border-light carouselButton">подробнее</button></a>
            </div>
        </div>
        {% else %}
        <div class="carousel-item">
            <img src="{{i.img.url}}" class="d-block w-100 carousel-img" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h1 class="carouselTextH1">{{i.name}}</h1>
                <p>{{i.description|truncatechars:250}}</p>
                <a href="{% url 'BoardShop:ProductView' i.id%}"><button type="button"
                        class="btn btn-dark border border-light carouselButton">подробнее</button></a>
            </div>
        </div>
        {% endif %}
        {% endfor %}


        <!-- <div class="carousel-item">
                <img src="static/img/content/corusel.png" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                        <h1 class="carouselTextH1">{{rand1.name}}</h1>
                        <p>{{rand1.description|truncatechars:250}}</p>
                        <a href="/products/{{rand1.id}}"><button type="button"
                                class="btn btn-dark border border-light carouselButton">подробнее</button></a>
                    </div>
            </div>
            <div class="carousel-item">
                <img src="static/img/content/corusel.png" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                        <h1 class="carouselTextH1">{{rand2.name}}</h1>
                        <p>{{rand2.description|truncatechars:250}}</p>
                        <a href="/products/{{rand2.id}}"><button type="button"
                                class="btn btn-dark border border-light carouselButton">подробнее</button></a>
                    </div>
            </div> -->

    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
        data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
        data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
{% endblock content %}

KeyCase/BoardShop/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Sign in</button>
  </form>
{% endblock %}

KeyCase/BoardShop/templates/product.html
{% extends 'base.html' %} {% block content %}
<div
  style="
    position: fixed;
    background-color: aliceblue;
    border: solid;
    margin-left: 50px;
    margin-top: 120px;
    width: 836px;
    height: auto;
  "
>
  <p class="id">{{ item.id }}</p>
  <img
    style="width: 832px; height: auto"
    src="{{ product.img.url }}"
  />
  
</div>
<div style="position: absolute; left: 920px; top: 150px; width: 800px">
  <h1>{{product.name}}</h1>

  <form id="add-form" action="{% url 'BoardShop:addToCart' product.id %}" method="POST" style="margin: 0;">
    {% csrf_token %}
    <button class="buy" type="submit" style="margin: 10px; padding: 8px; font-size: 24px">
      {{ product.price }} ₽
    </button>
  </form>
  <p style="color: aliceblue; font-size: 16px">{{product.description|linebreaksbr}}</p>
</div>
{% endblock content %}

KeyCase/BoardShop/templates/products.html
{% extends 'base.html' %} {% block content %} <br /><br /><br /><br />

<h1>Клавиатуры</h1>
{% for product in products %}
<div class="card">
  <img style="width:100%; height:100%;"
    src="/static/img/content/{{ product.name }}.png"
    class="card-img-top"
    alt="..."
  />
  <div class="card-body">
    <h5 class="card-title">{{ product.name }}</h5>
    <a
      href="/products/{{ product.id }}"
      style="width: 80%; height: 70%; background-color: rgb(37, 37, 37)"
      class="btn btn-primary productBtn"
      >{{ product.price }} ₽</a
    >
  </div>
</div>
{% endfor %}
{% endblock content %}

KeyCase/BoardShop/templates/registration copy.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Sign in</button>
  </form>
{% endblock %}

KeyCase/BoardShop/templates/registration.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Sign in</button>
  </form>
{% endblock %}